on:
  push: 
    branches: [main]

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Setup PHP
  #       uses: shivammathur/setup-php@v2
  #       with:
  #         php-version: '8.1'

  #     - name: Install Dependencies
  #       run: composer install --prefer-dist --no-progress --no-suggest

  #     - name: Setup Laravel
  #       run: |
  #         cp .env.example .env
  #         php artisan config:clear
  #         php artisan cache:clear
  #         php artisan key:generate

  #     - name: Composer Audit
  #       run: composer audit

  #     - name: Composer Validate
  #       run: composer validate --no-check-all --strict

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '16'

  #     - name: Install Node.js Dependencies
  #       run: npm install

  #     - name: Build Vue.js
  #       run: npm run build

  deploy:
    # needs: [build]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Setup Environment File
        run: |
          cp .env.example .env
          sed -i 's/APP_NAME=Laravel/APP_NAME="Dating Service"/g' .env
          sed -i 's|APP_URL=http://localhost|APP_URL=${{ secrets.APP_URL }}|g' .env
          sed -i 's/DB_HOST=127.0.0.1/DB_HOST=${{ secrets.DB_HOST }}/g' .env
          sed -i 's/DB_DATABASE=laravel/DB_DATABASE=${{ secrets.DB_DATABASE }}/g' .env
          sed -i 's/DB_USERNAME=root/DB_USERNAME=${{ secrets.DB_USERNAME }}/g' .env
          sed -i 's/MAIL_USERNAME=null/MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}/g' .env
          sed -i 's/MAIL_PASSWORD=null/MAIL_PASSWORD="${{ secrets.MAIL_PASSWORD }}"/g' .env
          sed -i 's/MAIL_FROM_ADDRESS="hello@example.com"/MAIL_FROM_ADDRESS=${{ secrets.MAIL_USERNAME }}/g' .env
          sed -i 's/GOOGLE_MAPS_KEY=/GOOGLE_MAPS_KEY=${{ secrets.GOOGLE_MAPS_KEY }}/g' .env
          sed -i 's/PLISIO_SECRET_KEY=/PLISIO_SECRET_KEY=${{ secrets.PLISIO_SECRET_KEY }}/g' .env

      - name: Setup Laravel
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan key:generate
          php artisan storage:link

      - name: Permission setup
        run: |
          chmod -R 777 storage bootstrap/cache

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Node.js Dependencies
        run: npm install

      - name: Build Vue.js
        run: npm run build

      - name: Clean Up
        run: rm -rf node_modules

      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "./"
          target: "/var/www/date"

      - name: Run laravel commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script:
            cd /var/www/date && php artisan cache:clear && php artisan config:clear && php artisan view:clear && php artisan migrate